version: '3'

services:
  api-gateway-db:
    image: registry.gitlab.com/ugleiton/api-gateway-db:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      - TRINO_HOST=localhost
      - TRINO_PORT=8080
      